# PyTorch Basics Exercises
For these exercises we'll create a tensor and perform several operations on it.

<div class="alert alert-danger" style="margin: 10px"><strong>IMPORTANT NOTE!</strong> Make sure you don't run the cells directly above the example output shown, <br>otherwise you will end up writing over the example output!</div>

### 1. Perform standard imports
Import torch and NumPy

In [1]:
# CODE HERE
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 
import torch
import numpy as np

Looking in indexes: https://download.pytorch.org/whl/cu118
     ---------------------------------------- 0.0/6.2 MB ? eta -:--:--
     --- ------------------------------------ 0.6/6.2 MB 11.5 MB/s eta 0:00:01
     --------- ------------------------------ 1.4/6.2 MB 15.0 MB/s eta 0:00:01
     ------------- -------------------------- 2.1/6.2 MB 16.4 MB/s eta 0:00:01
     ------------------ --------------------- 2.9/6.2 MB 15.4 MB/s eta 0:00:01
     ------------------------ --------------- 3.8/6.2 MB 16.2 MB/s eta 0:00:01
     ----------------------------- ---------- 4.6/6.2 MB 16.2 MB/s eta 0:00:01
     ----------------------------------- ---- 5.5/6.2 MB 16.8 MB/s eta 0:00:01
     ---------------------------------------  6.2/6.2 MB 16.5 MB/s eta 0:00:01
     ---------------------------------------- 6.2/6.2 MB 14.6 MB/s eta 0:00:00
   ---------------------------------------- 0.0/2.7 GB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 GB 30.1 MB/s eta 0:01:31
   ----------

C:\Users\SEC\anaconda3\Lib\site-packages\torch\utils\_pytree.py:185: FutureWarning: optree is installed but the version is too old to support PyTorch Dynamo in C++ pytree. C++ pytree support is disabled. Please consider upgrading optree using `python3 -m pip install --upgrade 'optree>=0.13.0'`.
  warnings.warn(


### 2. Set the random seed for NumPy and PyTorch both to "42"
This allows us to share the same "random" results.

In [2]:
# CODE HERE
one = np.random.seed(42)
two =torch.manual_seed(42)


### 3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive)

In [3]:
# CODE HERE
arr = np.random.randint(0,5,size=6)


In [3]:
# DON'T WRITE HERE

[3 4 2 4 4 1]


### 4. Create a tensor "x" from the array above

In [4]:
# CODE HERE
x = torch.from_numpy(arr).to(torch.int32)


In [4]:
# DON'T WRITE HERE

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)


### 5. Change the dtype of x from 'int32' to 'int64'
Note: 'int64' is also called 'LongTensor'

In [5]:
# CODE HERE

x = x.to(torch.int64)

In [5]:
# DON'T WRITE HERE

torch.LongTensor


### 6. Reshape x into a 3x2 tensor
There are several ways to do this.

In [6]:
# CODE HERE

x_reshaped = x.reshape(3, 2)

In [6]:
# DON'T WRITE HERE

tensor([[3, 4],
        [2, 4],
        [4, 1]])


### 7. Return the right-hand column of tensor x

In [7]:
# CODE HERE

right_column = x[1]

In [7]:
# DON'T WRITE HERE

tensor([[4],
        [4],
        [1]])


### 8. Without changing x, return a tensor of square values of x
There are several ways to do this.

In [8]:
# CODE HERE

x_squared = x ** 2

In [8]:
# DON'T WRITE HERE

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])


### 9. Create a tensor "y" with the same number of elements as x, that can be matrix-multiplied with x
Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive).<br>
Think about what shape it should have to permit matrix multiplication.

In [9]:
# CODE HERE
y = torch.randint(0, 5, (2, 3))


In [9]:
# DON'T WRITE HERE

tensor([[2, 2, 1],
        [4, 1, 0]])


### 10. Find the matrix product of x and y

In [10]:
# CODE HERE
result = torch.mm(x_reshaped, y)
result = torch.mm(x_reshaped, y)
print("x reshaped:\n", x_reshaped)
print("y:\n", y)
print("Matrix multiplication result:\n",result)


x reshaped:
 tensor([[3, 4],
        [2, 4],
        [4, 1]])
y:
 tensor([[2, 2, 1],
        [4, 1, 0]])
Matrix multiplication result:
 tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])


In [11]:
# DON'T WRITE HERE

## Great job!